"""
Filename: firewall_rule_generator.py
Description: Reads a feed of identified malicious IP addresses and automatically 
             generates a bash script containing Linux iptables rules to drop 
             all inbound network traffic from those vectors.
"""

def generate_firewall_rules(ip_list_file, output_script):
    print(f"[*] Reading malicious IP feed from: {ip_list_file}...")
    
    # 1. Read the list of malicious IPs
    try:
        with open(ip_list_file, "r") as file:
            ips = [line.strip() for line in file if line.strip()]
    except FileNotFoundError:
        print(f"[ERROR] Could not find {ip_list_file}. Please check the path.")
        return

    # 2. Open the output bash script and write the iptables drop commands
    with open(output_script, "w") as script:
        script.write("#!/bin/bash\n")
        script.write("# Automated Firewall Drop Rules Generated by SOC Auto-Remediation Engine\n\n")
        
        for ip in ips:
            # Generate the specific iptables command to drop traffic from this IP
            rule = f"iptables -A INPUT -s {ip} -j DROP\n"
            script.write(rule)
            print(f"[RULE GENERATED] Drop traffic from {ip}")
            
        script.write("\necho 'All automated drop rules have been successfully applied.'\n")
        
    print(f"\n[SUCCESS] Firewall remediation script saved as '{output_script}'.")

if __name__ == "__main__":
    # Create a quick sample file of attacker IPs to test the generator
    sample_ips = "threat_feed.txt"
    with open(sample_ips, "w") as f:
        f.write("203.0.113.19\n198.51.100.88\n185.220.101.5\n")
        
    # Generate the blocking script
    generate_firewall_rules(sample_ips, "apply_block_rules.sh")